### ISSUE TITLE
Pls resolve this issue.

### ISSUE THREAD

**Issue by vimalku637** [razaghimahdi/Android-Loading-Dots#2]
java.lang.NullPointerException: Attempt to read from null array
        at com.razzaghimahdi78.dotsloading.LoadingDotsGetWave.onDetachedFromWindow(LoadingDotsGetWave.java:107)
        at android.view.View.dispatchDetachedFromWindow(View.java:20915)
        at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:4019)
        at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:4011)
        at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:4011)
        at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:4011)
        at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:4011)
        at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:4011)
        at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:4011)
        at android.view.ViewRootImpl.dispatchDetachedFromWindow(ViewRootImpl.java:4937)
        at android.view.ViewRootImpl.doDie(ViewRootImpl.java:8142)
        at android.view.ViewRootImpl.die(ViewRootImpl.java:8115)
        at android.view.WindowManagerGlobal.removeViewLocked(WindowManagerGlobal.java:537)
        at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:478)
        at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:141)
        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5363)
        at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:44)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2201)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:236)
        at android.app.ActivityThread.main(ActivityThread.java:8095)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:620)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1011)

**Comment by razaghimahdi** [comment]
I'll fix that then I'll let u know, tnx

**Comment by razaghimahdi** [comment]
Hi there, first of all sorry for this long time, please try new update, then let me know if everything is alright or not❤

**Comment by rtz333** [comment]
java.lang.NullPointerException: Attempt to read from null array
                                                                                                    	at com.razzaghimahdi78.dotsloading.linear.LoadingDancing.onDetachedFromWindow(LoadingDancing.java:72)
                                                                                                    	at android.view.View.dispatchDetachedFromWindow(View.java:22538)
                                                                                                    	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:4169)
                                                                                                    	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:4161)
                                                                                                    	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:4161)
                                                                                                    	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:4161)
                                                                                                    	at android.view.ViewGroup.removeViewInternal(ViewGroup.java:5806)
                                                                                                    	at android.view.ViewGroup.removeViewAt(ViewGroup.java:5753)
                                                                                                    	at androidx.recyclerview.widget.RecyclerView$5.removeViewAt(RecyclerView.java:882)
                                                                                                    	at androidx.recyclerview.widget.ChildHelper.removeViewIfHidden(ChildHelper.java:386)
                                                                                                    	at androidx.recyclerview.widget.RecyclerView.removeAnimatingView(RecyclerView.java:1452)
                                                                                                    	at androidx.recyclerview.widget.RecyclerView$ItemAnimatorRestoreListener.onAnimationFinished(RecyclerView.java:12699)
                                                                                                    	at androidx.recyclerview.widget.RecyclerView$ItemAnimator.dispatchAnimationFinished(RecyclerView.java:13199)
                                                                                                    	at androidx.recyclerview.widget.SimpleItemAnimator.dispatchRemoveFinished(SimpleItemAnimator.java:277)
                                                                                                    	at androidx.recyclerview.widget.DefaultItemAnimator$4.onAnimationEnd(DefaultItemAnimator.java:213)
                                                                                                    	at android.view.ViewPropertyAnimator$AnimatorEventListener.onAnimationEnd(ViewPropertyAnimator.java:1115)
                                                                                                    	at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:600)
                                                                                                    	at android.animation.ValueAnimator.endAnimation(ValueAnimator.java:1333)
                                                                                                    	at android.animation.ValueAnimator.doAnimationFrame(ValueAnimator.java:1575)
                                                                                                    	at android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:307)
                                                                                                    	at android.animation.AnimationHandler.-$$Nest$mdoAnimationFrame(Unknown Source:0)
                                                                                                    	at android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:86)
                                                                                                    	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1299)
                                                                                                    	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1309)
                                                                                                    	at android.view.Choreographer.doCallbacks(Choreographer.java:923)
                                                                                                    	at android.view.Choreographer.doFrame(Choreographer.java:847)
                                                                                                    	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1283)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:942)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:226)
                                                                                                    	at android.os.Looper.loop(Looper.java:313)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8757)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)

**Comment by rtz333** [comment]
same error version 'com.github.razaghimahdi:Android-Loading-Dots:1.3.0'

**Comment by razaghimahdi** [comment]
@rtz333 would you share codes with me please? it seems it's not from the library. 
also what happened exactly?
