### ISSUE TITLE
crash 

### ISSUE THREAD

**Issue by mohamedAppetito** [razaghimahdi/Android-Loading-Dots#6]
Attempt to read from null array  at at com.razzaghimahdi78.dotsloading.linear.LoadingWavy.onDetachedFromWindow(LoadingWavy.java:81)

**Comment by r1cht4** [comment]
Same for me:

java.lang.NullPointerException: Attempt to read from null array 

at com.razzaghimahdi78.dotsloading.linear.LoadingWavy.onDetachedFromWindow(LoadingWavy.java:81) 

at android.view.View.dispatchDetachedFromWindow(View.java:21417)
